/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiProduct: typeof import('./components/swipers/ai-product.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    ModelBox: typeof import('./components/thisai/ModelBox.vue')['default']
    ModelIntro: typeof import('./components/thisai/ModelIntro.vue')['default']
    NavTab: typeof import('./components/tabs/NavTab.vue')['default']
    NavTabItem: typeof import('./components/tabs/NavTabItem.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderAnnounce: typeof import('./components/thisai/SliderAnnounce.vue')['default']
    SliderIndex: typeof import('./components/thisai/SliderIndex.vue')['default']
    SliderIntro: typeof import('./components/thisai/SliderIntro.vue')['default']
    SliderSlogan: typeof import('./components/thisai/SliderSlogan.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    Thisai: typeof import('./components/thisai/thisai.vue')['default']
    TouchProduct: typeof import('./components/swipers/touch-product.vue')['default']
    TSelect: typeof import('./components/tabs/TSelect.vue')['default']
    TSelectItem: typeof import('./components/tabs/TSelectItem.vue')['default']
  }
}
